# Config file for Google APp Engine
entrypoint: python app.py
version: 1
runtime: python
api_version: 1
threadsafe: yes

libraries:
- name: flask
  version: latest
- name: youtube-dl
  version: latest
- name: pafy
  version: latest
    
handlers:
- url: /.*
  script: app.py
- url: /static
  static_dir: static
